export { default as Discord } from "./Discord";
export { default as Facebook } from "./Facebook";
export { default as Github } from "./Github";
export { default as Instagram } from "./Instagram";
export { default as Linkedin } from "./Linkedin";
export { default as Spotify } from "./Spotify";
export { default as Telegram } from "./Telegram";
export { default as Twitter } from "./Twitter";
export { default as Alien } from "./Alien";
